### ISSUE TITLE
Сторонний сервис, отвечающий за получение receipt не работает

### ISSUE THREAD

**Issue by ghost** [atckun/VkNetMusicBypass#10]
Как вариант - форкнуть получение receipt's от гугла из https://github.com/Rast1234/VOffline/tree/master/VOffline/Services/Token

https://github.com/hikiblade/VkNet.AudioBypass/blob/80662996b1d676b832cd7119eb7fbdd247092d01/VkNet.AudioBypassService/ReceiptParser.cs#L24-L29

**Comment by saber-nyan** [comment]
Ща что-нибудь придумаем...

**Comment by saber-nyan** [comment]
Как крайний случай -- можно парсить HTML с `m.vk.com` и декодировать URL, алгоритм описан [здесь](https://github.com/python273/vk_api/blob/master/vk_api/audio_url_decoder.py).
Но пока смотрю VOffline.

**Comment by Rast1234** [comment]
если что, мопед не мой. я портанул на шарп вот этот проект: https://github.com/vodka2/vk-audio-token

**Comment by saber-nyan** [comment]
@Rast1234 ну все равно спасибо, так проще было~

Сейчас протестирую и будет PR.

Всплыла ошибочка, расследую дальше...

**Comment by saber-nyan** [comment]
Отловил багу, проблема со `scope`, юзерагентом и новой версией API.<br/>
![image](https://user-images.githubusercontent.com/25345196/51429002-29a6c200-1c1b-11e9-922b-ab6f2e4b50dd.png)
