### ISSUE TITLE
AudioDownloadExtensions.DownloadAsync

### ISSUE THREAD

**Issue by StoryOff** [atckun/VkNetMusicBypass#14]
Здравствуйте. Если  я правильно понял, этот метод для скачивания аудио. Можете, пожалуйста, дать пример входного параметра "this IAudioCategoryAsync audioCategory", с другими двумя я смог разобраться, а вот 1ый совсем не понимаю(новичок)

**Comment by ghost** [comment]
Отпишите в телеграм @shelln1ght

вс, 17 нояб. 2019 г., 16:20 StoryOff <notifications@github.com>:
