### ISSUE TITLE
Разваливается с 1.53

### ISSUE THREAD

**Issue by CatWithAutism** [atckun/VkNetMusicBypass#16]
Разваливается в рантайме с VKNet 1.53. C 1.52 все окей
![image](https://user-images.githubusercontent.com/28768640/84326312-4d0e3c00-ab85-11ea-8869-b96b69bc8104.png)

**Comment by CatWithAutism** [comment]
Подсунуть ему Flurl я пробовал, там дальше разваливается
Всё брал с нугета

**Comment by i3ima** [comment]
Встретил абсолютно идентичную проблему, существует какое-нибудь временное решение?

**Comment by CatWithAutism** [comment]
> Встретил абсолютно идентичную проблему, существует какое-нибудь временное решение?

Версию понизь

**Comment by LGoldware** [comment]
Не получать исключения, да решает вопрос, а вот получать аудиозаписи теперь не выходит

**Comment by ghost** [comment]
> Не получать исключения, да решает вопрос, а вот получать аудиозаписи теперь не выходит

Отпиши в телеграм: @shelln1ght

**Comment by itsokto** [comment]
Fixed
