### ISSUE TITLE
Form element not found.

### ISSUE THREAD

**Issue by oldhowl** [atckun/VkNetMusicBypass#17]
Версия 1.6.0

При авторизации выкидывает следующее:

![image](https://user-images.githubusercontent.com/14297620/86768000-0b36bf80-c077-11ea-94f3-0666d1d3ae85.png)

```
VkNet.Exception.VkApiException: Form element not found.
   at VkNet.Utils.WebForm.GetFormNode()
   at VkNet.Utils.WebForm.ParseInputs()
   at VkNet.Utils.WebForm..ctor(WebCallResult result)
   at VkNet.Utils.WebForm.From(WebCallResult result)
   at VkNet.Utils.Browser.FilledLoginFormAsync(String email, String password, WebCallResult authorizeUrlResult)
   at VkNet.Utils.Browser.NextStepAsync(WebCallResult formResult)
   at VkNet.Utils.Browser.AuthorizeAsync()
   at VkNet.VkApi.BaseAuthorize(IApiAuthParams authParams)
   at VkNet.VkApi.AuthorizeWithAntiCaptcha(IApiAuthParams authParams)
   at VkNet.VkApi.Authorize(IApiAuthParams params)
   at VkNet.VkApi.Authorize(ApiAuthParams params)
```

**Comment by itsokto** [comment]
Вы не подключили bypass

**Comment by oldhowl** [comment]
> Вы не подключили bypass

Зарезолвил сервис в Startup классе. У меня asp.net core. 

Судя по стектрейсу тут какая то ошибка связанная с самой авторизацией и VkApi оберткой, может форму авторизации изменили? Я так понимаю из трейса что VkNet эмулирует действия браузера

**Comment by itsokto** [comment]
У вас не подключен bypass. вызов авторизации был был не в Browser, а в VkAndroidAuthorization

**Comment by oldhowl** [comment]
> У вас не подключен bypass. вызов авторизации был был не в Browser, а в VkAndroidAuthorization


с этим разобрался. создал ServiceCollection в конструкторе своего сервиса Vk и заинжектил его в VkApi, но появился следующий вопрос. URI приходит на m3u8 файл

https://psv4.vkuseraudio.net/c815527/u474499312/27a6b78da93/audios/62e45bcb588d/index.m3u8?extra=8sGlAvT5ZJ-7btxI7qcmUnrvjHLISxZCdoBWQwvz8imRdj-LW6eQyOQ2mDQikJnM39ASmwwVO0V1tF1dq6C-cNfgTIaoFH9vvIq4KLwkbMfVAZMxoT02-oQXHpkA_I0PDxO2Sp5FeUhl1dgvJu-18Ys&long_chunk=1

не понимаю как получить сам аудио файл

**Comment by itsokto** [comment]
[VkNet FAQ](https://github.com/vknet/vk/wiki/FAQ#%D0%9A%D0%B0%D0%BA-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C-%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D1%83-%D0%BD%D0%B0-%D0%B0%D1%83%D0%B4%D0%B8%D0%BE%D0%B7%D0%B0%D0%BF%D0%B8%D0%B8%D1%81%D1%8C-%D0%B2-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B5-mp3)

**Comment by oldhowl** [comment]
> [VkNet FAQ](https://github.com/vknet/vk/wiki/FAQ#%D0%9A%D0%B0%D0%BA-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C-%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D1%83-%D0%BD%D0%B0-%D0%B0%D1%83%D0%B4%D0%B8%D0%BE%D0%B7%D0%B0%D0%BF%D0%B8%D0%B8%D1%81%D1%8C-%D0%B2-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B5-mp3)


Спасибо. Т.к. это по большей части фича этой библиотеки, было бы разумно добавить инфо об vp3 на главную в README.
