### ISSUE TITLE
Ошибка при авторизации

### ISSUE THREAD

**Issue by vityaSteam** [atckun/VkNetMusicBypass#19]
При вызове метода Authorize появляется исключение: Метод не найден: "Void VkNet.Utils.VkErrors.IfErrorThrowException(System.String)"

**Comment by Karmageddonium** [comment]
Подтверждаю, та же фигня

**Comment by Karmageddonium** [comment]
@vityaSteam Нашел решение. Опусти версию VkNet до 1.65.0 (c 1.68.0 возникает жта ошибка)

**Comment by ghost** [comment]
В VkNet изменилась сигнатура метода
 https://github.com/vknet/vk/blob/develop/VkNet/Utils/VkErrors.cs#L136
