### ISSUE TITLE
Doesn't it work anymore?

### ISSUE THREAD

**Issue by ryletko** [atckun/VkNetMusicBypass#22]
Значит ли данный результат, что обход больше не работает?

![image](https://user-images.githubusercontent.com/11015665/178659027-bb7a1096-35d2-42c5-a34e-c2d35f39282d.png)

**Comment by itsokto** [comment]
пожалуйста, приведите пример кода/ссылку на репозиторий где это воспроизводится

**Comment by itsokto** [comment]
на скрине используется токен в методе авторизации - возможно в этом и причина. если токен был получен до использования bypass - 100% он не валиден для работы с методами audio. авторизуйтесь снова через логин/пароль и используйте полученный токен
