### ISSUE TITLE
System.TypeLoadException: Method 'AuthorizeAsync' in type 'VkNet.AudioBypassService.VkAndroidAuthorization' does not have an implementation.

### ISSUE THREAD

**Issue by rhiskey** [atckun/VkNetMusicBypass#28]
После выполнения строки из [документации](https://github.com/0xshelln1ght/VkNet.AudioBypass#%D0%BA%D0%B0%D0%BA-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C) `services.AddAudioBypass();`  возникает ошибка в версиях 1.7.3. и 1.7.4:

```csharp
System.TypeLoadException: Method 'AuthorizeAsync' in type 'VkNet.AudioBypassService.VkAndroidAuthorization' from assembly 'VkNet.AudioBypassService, Version=1.7.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at VkNet.AudioBypassService.Extensions.AudioBypassServiceCollection.AddAudioBypass(IServiceCollection services)
```

**Comment by wnglsss** [comment]
Вам нужно понизить версию VkNet до 1.65.0.

**Comment by maestroant** [comment]
Не работает и старая версия!

**Comment by rhiskey** [comment]
> Не работает и старая версия! 

Похоже забросили пакет😔

**Comment by rhiskey** [comment]
Пофиксили в 1.7.5, вроде работает норм.
