### ISSUE TITLE
Unable to resolve service VkNet.Utils.RestClient

### ISSUE THREAD

**Issue by Shark-vil** [atckun/VkNetMusicBypass#33]
Ошибка появилась сама собой. Не знаю, это проблема на моей стороне, или VK опять что-то поменяли, из-за чего расширение сломалось. Объект VkApi даже не успевает создастся, сразу вылетает.

```
Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger`1[VkNet.Utils.RestClient]' while attempting to activate 'VkNet.AudioBypassService.Utils.RestClientWithUserAgent'.
```

**Comment by mokshinpv** [comment]
Добрый день!
Если я правильно понял, это исправление уже замержено (этот коммит: https://github.com/inyutin-maxim/VkNet.AudioBypass/commit/9f478665b2bbfcd90b42e87908d3b4211458b180), но в Nuget находится старая версия.
Если я прав, и текущая версия в репозитории рабочая, то выложите, пожалуйста, новую версию в Nuget.
@inyutin-maxim
