### ISSUE TITLE
Хост для получения receipt не резолвится

### ISSUE THREAD

**Issue by saber-nyan** [atckun/VkNetMusicBypass#9]
https://github.com/hikiblade/VkNet.AudioBypass/blob/80662996b1d676b832cd7119eb7fbdd247092d01/VkNet.AudioBypassService/ReceiptParser.cs#L24-L29
Предлагаю дать возможность указать его вручную или оживить!

**Comment by ghost** [comment]
https://github.com/hikiblade/VkNet.AudioBypass/issues/10
